### ISSUE TITLE
Kim To-Do

### ISSUE THREAD

**Issue by KimothyPepper** [ca1tlin22/simple-chat-app#10]
- [x] Research notification pop ups
- [x] Make new code pen
- [ ] Code notification bar
- [ ] COMPLETE 🐶 🐼
